name: flutter_conf_latam
description: "FlutterConf - LATAM"
publish_to: 'none'
version: 0.1.2+6

environment:
  sdk: ^3.7.0

dependencies:
  
  agenda_repository:
    path: packages/agenda_repository
  conf_auth_data_source:
    path: packages/conf_auth_data_source
  conf_auth_repository:
    path: packages/conf_auth_repository
  conf_cache:
    path: packages/conf_cache
  conf_cloud_functions_data_source:
    path: packages/conf_cloud_functions_data_source
  conf_core:
    path: packages/conf_core
  conf_shared_models:
    path: packages/conf_shared_models
  conf_ui_kit:
    path: packages/conf_ui_kit
  connectivity_monitor:
    path: packages/connectivity_monitor
  equatable: ^2.0.7
  firebase_core: ^3.15.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  go_router: ^15.1.3
  intl: ^0.20.2
  path_provider: ^2.1.5
  share_plus: ^11.0.0
  speakers_repository:
    path: packages/speakers_repository
  sponsors_repository:
    path: packages/sponsors_repository
  url_launcher: ^6.3.1
  user_repository: 
    path: packages/user_repository
  
dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/udla.webp
    - assets/icons/agenda/
    - assets/icons/

  generate: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/launcher_icon/launcher_icon.png"
