name: conf_ui_kit
description: "UI Kit for FlutterConf LATAM"
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  animated_flip_counter: ^0.3.4
  cached_network_image: 
  conf_shared_models:
    path: ../conf_shared_models
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.0
  google_fonts: ^6.2.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:

  assets:
    - assets/images/waving_dash.svg
    - assets/social_icons/
