name: conf_ui_kit
description: "UI Kit for FlutterConf LATAM"
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: ^3.7.0
  flutter: ">=3.29.0"

dependencies:
  animated_flip_counter: ^0.3.4
  cached_network_image: ^3.4.1
  conf_core:
    path: ../conf_core
  conf_shared_models:
    path: ../conf_shared_models
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.20.2

flutter_gen:
  output: lib/src/gen/

  integrations:
    flutter_svg: true

  assets:
    outputs:
      package_parameter_enabled: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/brand/
    - assets/icons/
    - assets/images/
    - assets/social_icons/
  
  fonts:
    - family: Recoleta
      fonts:
        - asset: assets/fonts/recoleta-black.otf
          weight: 900
