name: conf_cache
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  clock: ^1.1.2
  flutter:
    sdk: flutter
  hive: ^2.2.3
  path_provider: ^2.1.5

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  mockito: ^5.4.6
  path: ^1.9.1
  very_good_analysis: ^7.0.0

flutter:
