name: conf_shared_models
description: "Shared models for FlutterConf LATAM"
version: 0.0.1
homepage:

environment:
  sdk: ^3.7.0

dependencies:
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  very_good_analysis: ^7.0.0

flutter:

