name: conf_auth_data_source
description: Auth DataSource
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  crypto: ^3.0.6
  firebase_auth: ^5.5.3
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1

dev_dependencies:
  very_good_analysis: ^7.0.0
